version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s [%(levelname)7s] %(name)s - %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  console:
    class: "logging.StreamHandler"
    level: "INFO"
    formatter: "default"
    stream: "ext://sys.stdout"
loggers:
  "":
    level: "DEBUG"
    handlers:
      - "console"
